#!/usr/bin/env bash

echo "Setting up Sequre ..."

export PID=$2
SEQURE_STDLIB=$SEQURE_PATH/stdlib/sequre

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export CP_OPTIONS=-uf
elif [[ "$OSTYPE" == "darwin"* ]]; then
    export CP_OPTIONS=-f
fi

if [[ ${*:3} == *"--local"* ]]; then
    cp $CP_OPTIONS $SEQURE_STDLIB/network/unix_socket.codon $SEQURE_STDLIB/network/socket.codon
else
    cp $CP_OPTIONS $SEQURE_STDLIB/network/inet_socket.codon $SEQURE_STDLIB/network/socket.codon
fi

echo "Compiling $1 ..."
echo "Seq plugin searched at $SEQ_PATH ..."
echo "Sequre plugin searched at $SEQURE_PATH ..."
GC_INITIAL_HEAP_SIZE=8179869184 GC_LIMIT=8179869184 codon run -plugin $SEQURE_PATH -plugin $SEQ_PATH -release $1 ${*:3}
