#!/usr/bin/env bash

echo "Setting up Sequre ..."

export PID=$2

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export CP_OPTIONS=-ruf
elif [[ "$OSTYPE" == "darwin"* ]]; then
    export CP_OPTIONS=-Rf
fi

cp $CP_OPTIONS dsl/* seq/stdlib/sequre/
if [[ ${*:3} == *"--local"* ]]; then
    mv seq/stdlib/sequre/network/unix_socket.seq seq/stdlib/sequre/network/socket.seq
else
    mv seq/stdlib/sequre/network/inet_socket.seq seq/stdlib/sequre/network/socket.seq
fi

echo "Compiling $1 ..."
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    seq/build/seqc run -release $1 ${*:3}
elif [[ "$OSTYPE" == "darwin"* ]]; then
    seq/build/seqc run -release $1 ${*:3}
fi
