
## Output and cache paths
output_dir = "out/gwas-toy/party1"
cache_dir = "cache/gwas-toy/party1"

## relatives specific parameters
simple_data_path = "../../../data/king/king_sample.txt"
separator = ' '
number_of_rows = 64
number_of_columns = 8192
local_num_threads = 1
