
## Output and cache paths
output_dir = "out/gwas-toy/party2"
cache_dir = "cache/gwas-toy/party2"


## relatives specific parameters
simple_data_path = "../../../data/king/king_sample.txt"
separator = ' '
number_of_rows = 8
number_of_columns = 8192
local_num_threads = 1