
## Output and cache paths
output_dir = "out/gwas-toy/party1"
cache_dir = "cache/gwas-toy/party1"

## relatives specific parameters
simple_data_path = "../../data/king/geno_pca_input.txt" #"notebooks/matrix.csv" #
separator = ' '
number_of_rows = 16
number_of_columns = 8192
starting_index = 0

