
## Output and cache paths
output_dir = "out/gwas-toy/party2"
cache_dir = "cache/gwas-toy/party2"


## relatives specific parameters
simple_data_path = "data/geno_pca_input.txt" #"notebooks/matrix.csv" #
separator = ' '
number_of_rows = 16
number_of_columns = 32
starting_index = 0