verbose = false
run_scenarios = true
run_pymice = true
run_simice = false
run_real_setup = false
dump_data = true

scenarios_runs_count = 1
pymice_runs_count = 1
simice_runs_count = 1
real_setup_runs_count = 1

scenarios_rows = 500
scenarios_cols = 2
simice_rows = 500
simice_cols = 10
simice_miss_rows = 150

mi_factor = 5
miss_val = 0.0
scenarios_miss_col = 0
real_setup_outlier_threshold = 3000.0
im_epochs = 20
fm_epochs = 40
im_noise_scale = 0.01
