verbose = false
run_scenarios = false
run_pymice = false
run_simice = false
run_real_setup = true
dump_data = true

scenarios_runs_count = 10
pymice_runs_count = 10
simice_runs_count = 10
real_setup_runs_count = 1

paper_scenario_rows = 5000
paper_scenario_cols = 2
midn_scenario_rows = 5000
midn_scenario_cols = 10
midn_miss_rows_count = 1500

mi_factor = 5
miss_val = 0.0
scenarios_miss_col = 0
real_setup_outlier_threshold = 3000.0
im_epochs = 40
fm_epochs = 40
im_noise_scale = 0.01
