num_main_parties = 2
hub_party_id = 1
debug = true

## Crypto parameters
# Options: PN12QP109, PN13QP218, PN14QP438, PN15QP880, PN16QP1761
# Defined in ckks/params.go in Lattigo library
ckks_params = "PN14QP438"

# MPC parameters
div_sqrt_max_len = 100000 # TODO: currently ignored
mpc_num_threads = 7
mpc_field_size = 256
mpc_data_bits = 60
mpc_frac_bits = 30
mpc_boolean_shares = true

## Output and cache paths
output_dir = "out/"
cache_dir = "cache/"

## Relative Matching Parameters
comparison_map = {"1" = [2]}

## Networking parameters
# Party with a smaller ID listens for connection
# Port only needed for the listener
[servers.party0]
ipaddr = "127.0.0.1"
ports  = {party1 = "8010", party2 = "8020"}

[servers.party1]
ipaddr = "127.0.0.1"
ports  = {party2 = "8030"}

[servers.party2]
ipaddr = "127.0.0.1"
ports  = {}

