name: Sequre CI

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    permissions:
      contents: write
    steps:
      - name: Create Release
        if: contains(github.ref, 'tags/v')
        id: create_release
        uses: ncipollo/release-action@v1

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux-x86_64
            artifact: manylinux-x86_64
            dockerfile: Dockerfile.x86_64
          - os: macos-15
            arch: darwin-arm64
            artifact: darwin-arm64
    runs-on: ${{ matrix.os }}
    name: Sequre CI (${{ matrix.arch }})
    needs: create_release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd .github/actions/build-manylinux && docker build -t sequre-build -f ${{ matrix.dockerfile }} .
          cd ${{ github.workspace }}
          docker run -v $(pwd):/github/workspace sequre-build

      - name: Build (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          sudo mkdir -p /opt/llvm-codon
          sudo chown -R $(whoami) /opt
          bash .github/actions/build-manylinux/entrypoint.sh ${{ github.workspace }}

      - name: Upload Release Asset
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./sequre-${{ matrix.arch }}.tar.gz
          asset_name: sequre-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: sequre-${{ matrix.arch }}.tar.gz
