name: Sequre CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Check
        if: contains(github.ref, 'tags/v')
        id: check
        run: echo "MAKE_RELEASE=true" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Output Release URL File
        if: ${{ env.MAKE_RELEASE == 'true' }}
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt

      - name: Save Release URL File for Publish
        if: ${{ env.MAKE_RELEASE == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: release_url
          path: release_url.txt

  manylinux:
    runs-on: ubuntu-latest
    name: Sequre CI (manylinux)
    needs: [ release ]
    steps:
      - uses: actions/checkout@v2

      - name: Main
        uses: ./.github/actions/build-manylinux

      - name: Load Release URL File
        if: contains(github.ref, 'tags/v')
        uses: actions/download-artifact@v3
        with:
          name: release_url

      - name: Get Release URL
        id: get_release_url
        if: contains(github.ref, 'tags/v')
        run: |
          echo "file_name=${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/v}" >> $GITHUB_ENV
          value=$(cat release_url.txt)
          echo "upload_url=$value" >> $GITHUB_ENV
        env:
          TAG_REF_NAME: ${{ github.ref }}
          REPOSITORY_NAME: ${{ github.repository }}

      - name: Upload Release Asset
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./sequre-linux-x86_64.tar.gz
          asset_name: sequre-linux-x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: manylinux-x86_64
          path: sequre-linux-x86_64.tar.gz

  main:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    runs-on: ${{ matrix.os }}
    name: Sequre CI
    needs: [ release ]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo bash .github/actions/build-manylinux/entrypoint.sh $(pwd)

      - name: Load Release URL File
        if: contains(github.ref, 'tags/v')
        uses: actions/download-artifact@v3
        with:
          name: release_url

      - name: Get Release URL
        id: get_release_url
        if: contains(github.ref, 'tags/v')
        run: |
          echo "file_name=${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/v}" >> $GITHUB_ENV
          value=$(cat release_url.txt)
          echo "upload_url=$value" >> $GITHUB_ENV
        env:
          TAG_REF_NAME: ${{ github.ref }}
          REPOSITORY_NAME: ${{ github.repository }}

      - name: Upload Release Asset
        if: contains(github.ref, 'tags/v') && startsWith(matrix.os, 'macos')
  
