name: Sequre CI

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    permissions:
      contents: write
    steps:
      - name: Create Release
        if: contains(github.ref, 'tags/v')
        id: create_release
        uses: ncipollo/release-action@v1

  manylinux:
    runs-on: ubuntu-latest
    name: Sequre CI (manylinux)
    needs: create_release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Main
        uses: ./.github/actions/build-manylinux

      - name: Upload Release Asset
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./sequre-linux-x86_64.tar.gz
          asset_name: sequre-linux-x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: manylinux-x86_64
          path: sequre-linux-x86_64.tar.gz

  main:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Sequre CI
    needs: create_release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Linux Setup
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo "LIBEXT=so" >> $GITHUB_ENV
          echo "OS_NAME=linux" >> $GITHUB_ENV

      - name: Build
        run: |
          sudo bash .github/actions/build-manylinux/entrypoint.sh $(pwd)

      - name: Artifact Environment
        run: |
          echo "SEQURE_BUILD_ARCHIVE=sequre-$(uname -s | awk '{print tolower($0)}')-$(uname -m).tar.gz" >> $GITHUB_ENV

      - name: Prepare Artifacts
        run: |
          tar -czf ${SEQURE_BUILD_ARCHIVE} sequre-deploy
          du -sh sequre-deploy

      - name: Upload Artifacts
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-x86_64
          path: sequre-linux-x86_64.tar.gz
