# This is a basic test workflow that executes substantial tests

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build dependencies and test all
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone Seq
        run: |
          git clone https://github.com/HarisSmajlovic/seq.git
          cd seq
          git checkout feature/sequre-v0.0.1

      - name: Add Sequre DSL to Seq
        run: |
          mkdir seq/stdlib/sequre
          cp -r dsl/* seq/stdlib/sequre/

      - name: Build
        run: |
          cd seq
          mkdir build
          ln -s $(pwd)/deps/lib/libomp.so $(pwd)/build/libomp.so
          export SEQ_HTSLIB=$(pwd)/deps/lib/libhts.so
          mkdir build
          (cd build && cmake .. -DCMAKE_BUILD_TYPE=Release \
                                -DLLVM_DIR=$(llvm-config --cmakedir) \
                                -DCMAKE_C_COMPILER=${CC} \
                                -DCMAKE_CXX_COMPILER=${CXX})
          cmake --build build --config Release
        env:
          CC: clang
          CXX: clang++
      
      - name: Run tests
        run:  seq/build/seqc run -release scripts/invoke.seq run-tests --unit --local
  